algoritmo "semnome"
// Função :
// Autor :
// Data : 24/03/2022
// Seção de Declarações 
var  a , b : inteiro

inicio
EScreval ("   Contagem inteligente      ")
Escreval ("Inicio : ")
         leia(a)
Escreval("Fim : ")
         leia (b)
Escreval (a)
enquanto (a<>b) faca

        se (a<b) entao
        a<-a+1
        senao
        a<-a-1
       fimse
        EScreval (a)

fimenquanto

// Seção de Comandos 
fimalgoritmo
