algoritmo "semnome"
// Função :
// Autor :
// Data : 14/04/2022
// Seção de Declarações 
var
m,s:caractere
c:inteiro
  PROCEDIMENTO vai()
  inicio
  Escreval("EU vou conseguir em nome de JEsus Cristo amém")
  fimprocedimento
  
  
inicio
c<-0
enquanto c<5 faca
escreval ("tu vai conseguir ?")
leia (m)
Se (m = "s")entao
vai()
vai()
vai()
senao
Escreval("diga sim zé mané")
fimse
c<-c+1
fimenquanto

// Seção de Comandos 
fimalgoritmo
